### ISSUE TITLE
外观比较简洁清新，只适配了1080p其他分辨率有些问题

### ISSUE THREAD

**Issue by xiaoyaomimi** [dcq123/StepView#1]

**Comment by dcq123** [comment]
我在模拟器上试了其他分辨率的，没有发现什么问题。不知道你的是什么分辨率，出现的问题是什么样的问题；

**Comment by xiaoyaomimi** [comment]
在小米真机720p下，会出现第一条信息测量不准确，第一个item占满了整个屏幕，出现一大片空白，后面的item正常，还有就是viewlayout下圆圈的半径默认值需要改下，不然画的时候会是负数

**Comment by xiaoyaomimi** [comment]
刚刚在720p模拟器下也试了，还是出现了同样的问题

**Comment by dcq123** [comment]
我的在720模拟器上一切正常。你的是直接跑demo就存在这种问题吗？


原始邮件
发件人:xiaoyaomiminotifications@github.com
收件人:dcq123/StepViewStepView@noreply.github.com
抄送:dcqqing_soft@sina.cn; Commentcomment@noreply.github.com
发送时间:2016年12月22日(周四) 12:33
主题:Re: [dcq123/StepView] 外观比较简洁清新，只适配了1080p其他分辨率有些问题 (#1)


刚刚在720p模拟器下也试了，还是出现了同样的问题

**Comment by xiaoyaomimi** [comment]
找到原因了，使用stepview.setData()就会有问题，如果使用setDataAndView()就没有问题

**Comment by dcq123** [comment]
布局高度的设置问题，目前已修复，多谢提出问题~

**Comment by xiaoyaomimi** [comment]
O(∩_∩)O哈哈~，谢谢你的控件才对，我也懒得自己写了

**Comment by dcq123** [comment]
O(∩_∩)O
